### ISSUE TITLE
Zombie refresh less

### ISSUE THREAD

**Issue by skyvzla** [mihayy5/mtadayz07#1]
Players enter the server can only refresh 5 zombie then it is no longer new zombies
I guess the core client.lua file
Position in 319 -332 line row

```
[setTimer(function()
	if getElementData(getLocalPlayer(), "logedin") then
		if (not isElementInWater(getLocalPlayer())) then
			if ((getElementData(getLocalPlayer(), "spawnedzombies")+1) <= 5) then  
           --Estimation problem here -- Above the line
				local x,y,z = getElementPosition(getLocalPlayer());
				local material,hX,hY,hz = isObjectAroundPlayer(getLocalPlayer(), 30, 3);
				local gp = getGroundPosition(x, y, z);
				if (material == 0 and not isInBuilding(hX, hY, hz)) then
					triggerServerEvent("createZomieForPlayer", getLocalPlayer(), hX, hY, (gp+2));
				end
			end
		end
	end
end, 5000, 0);
```

You to fix it, I fix bad, technology is not enough!

**Comment by mihayy5** [comment]
Have you tested this issue? 
I'm pretty sure this is not an issue at all.
If you kill and/or get to far away from zombies new one's will be created, you can check **zombies.lua** for more info.

**Comment by skyvzla** [comment]
I tested the spawnedzombies every time you perform a +1 and so on his +5 will not be a zombie

**Comment by skyvzla** [comment]
pawnedzombies every time the execution of a +1 

when 6 zombies after he will exceed spawnedzombies+1<=5 
at this time his value of 6 will not be executed

Sorry, English is not good!

**Comment by skyvzla** [comment]
Zombies.lua no place to control the number of zombies near the player!

**Comment by mihayy5** [comment]
The idea is to not spawn more that 5 zombies for a player to not make to much lag on the server.
You can always modify the 5 value to whatever you want.

**Comment by skyvzla** [comment]
spawnedzombies he will always increase will not be reduced so will only be out of the 5 zombies will not be out of the =5 can not be implemented will not refresh the zombie!

**Comment by skyvzla** [comment]
I know your idea is to let the server is not lagging behind, but the zombies will not refresh

**Comment by skyvzla** [comment]
You can test a local test out of 5 zombies and then you let them refresh themselves without you will find no longer a zombie

**Comment by mihayy5** [comment]
If you do not kill or get far away from that zombies they will not re-spawn.
Anyway let me test it to make sure there are no errors in the code.

**Comment by skyvzla** [comment]
I hope you will have a good test to make sure it doesn't appear in the wrong code

**Comment by skyvzla** [comment]
There are menu_client.lua files to remove the vehicle, will lead to more than the maximum value of the backpack space!

**Comment by mihayy5** [comment]
You mean, when you remove a part from vehicle? If yes then I already knew that.

**Comment by skyvzla** [comment]
yes

**Comment by mihayy5** [comment]
Since you are not the only one to report this issue I decided to fix it. (I always thought the people want it like this xd). Issue closed.

**Comment by skyvzla** [comment]
The value of spawnedzombies will increase, unless the player dies or re - log will be reset to 0

**Comment by skyvzla** [comment]
So you use the "spawnedzombies<=5" is not reliable!

**Comment by skyvzla** [comment]
Sorry, you write code that is no problem!

**Comment by mihayy5** [comment]
Man I can't understand what are you talking about. Can you be more specific please?

**Comment by skyvzla** [comment]
Zombie scripts don't have problems!

**Comment by skyvzla** [comment]
Removal of vehicle parts will lead to the backpack space go beyond！

**Comment by mihayy5** [comment]
I've fixed that yesterday. You can check last commit: [34c975f](https://github.com/mihayy5/mtadayz07/commit/34c975f09ee2d9b3913ca46b4a62e2aade69c9cf).

**Comment by skyvzla** [comment]
thank you.
Find the problem and react to you!
