### ISSUE TITLE
Several known bugs

### ISSUE THREAD

**Issue by skyvzla** [mihayy5/mtadayz07#10]
Locate line 517 of the file 'vehicles.lua'

> ## setTimer(respawnDayZVehicle, 1800000, 1, id, x, y, z, v, col, getElementData(col, "MAX_Slots"));
Set to 1800 seconds, that is, 30 minutes
Line 527, **# end, (20*60000), 0);**  This cycle is executed once in 20 minutes, Regeneration occurs only after 30 minutes have elapsed

**Comment by skyvzla** [comment]
Detonated vehicles will also be detected !
Should be added:
## if(getElementData(col,"deadVehicle"))then return false end

**Comment by mihayy5** [comment]
Thanks for reporting this all done now.
BTW big update coming soon.
