### ISSUE TITLE
Vehicle spawn!

### ISSUE THREAD

**Issue by skyvzla** [mihayy5/mtadayz07#15]
Buna ziua!
Am fost în ultima versiune Feedback despre acest subiect!
În ceea ce privește renaștere vehicul.
Exploziile de vehicule și de apă sunt prezente, el va renaște din două!
În particular vehicles.lua 507 linii la 547 linii

> addEventHandler("onVehicleExplode", root,  function()
	for _,v in pairs(getVehicleOccupants(source)) do
		triggerEvent("kilLDayZPlayer", v);
	end
	local x1,y1,z1 = getElementPosition(source);
	local col = getElementData(source, "parent");
	local id,x,y,z = unpack(getElementData(col, "spawn"));
	setElementData(col, "deadVehicle", true);
	setElementData(source, "isExploded", true);
	if (getElementData(source, "dayzvehicle") == 1) then
		setTimer(respawnDayZVehicle, 1800000, 1, id, x, y, z, source, col);
	else
		setTimer(function(col, source)
			if isElement(col) then destroyElement(col); end
			if isElement(source) then destroyElement(source); end
		end, (5*60000), 1, col, source);
	end
	createExplosion((x1+4), (y1+1), z1, 4);
	createExplosion((x1+2), (y1-4), z1, 4);
	createExplosion((x1-1), (y1+5), z1, 4);
	createExplosion((x1-4), y1, (z1-2), 4);
end);

setTimer(function()
	for _,v in ipairs(getElementsByType("vehicle")) do
		if (getElementModel(v) ~= 453) then
			if isElementInWater(v) then
				local col = getElementData(v, "parent");
				local id,x,y,z = unpack(getElementData(col, "spawn"));
				if (getElementData(v, "dayzvehicle") == 1) then
					setTimer(respawnDayZVehicle, (5*60000), 1, id, x, y, z, v, col);
				else
					setTimer(function(col, v)
						if col then destroyElement(col); end
						if v then destroyElement(v); end
					end, (5*60000), 1, col, v);
				end
			end
		end
	end
end, (30*60000), 0);

să
'if (getElementModel(v) ~= 453) then' 
Adăugați o linie în spatele
'if(getElementData(getElementData(v, "parent"),"deadVehicle") ~=true)then'

Eu folosesc Google traduce, picătură limba mea tradus în limba română, ar trebui să existe diferențe lingvistice

**Comment by skyvzla** [comment]
explosion and water 
When both conditions are met
Două va renaște（Will be reborn two）

**Comment by mihayy5** [comment]
Is this what you mean?
```
setTimer(function()
	for _,v in ipairs(getElementsByType("vehicle")) do
		if (getElementModel(v) ~= 453) then
			local col = getElementData(v, "parent");
			if not getElementData(col, "deadVehicle") then
				if isElementInWater(v) then
					local id,x,y,z = unpack(getElementData(col, "spawn"));
					if (getElementData(v, "dayzvehicle") == 1) then
						setTimer(respawnDayZVehicle, (5*60000), 1, id, x, y, z, v, col);
					else
						setTimer(function(col, v)
							if col then destroyElement(col); end
							if v then destroyElement(v); end
						end, (5*60000), 1, col, v);
					end
				end
			end
		end
	end
end, (30*60000), 0);
```

Next time use English for translate.

**Comment by skyvzla** [comment]
Yes！

**Comment by mihayy5** [comment]
OK thanks for the feedback.
