### ISSUE TITLE
Equip/Weapon system is glitched.

### ISSUE THREAD

**Issue by rivor2** [mihayy5/mtadayz07#16]
Hey,

Nice work on updating this mod. Not sure or you have noticed that Equip/Weapon system is glitched/not working as supposed to be. First is that you can change to every weapon and have them all in your inventory equipped(this happend once for some reason tried again didnt work, maybe it was on older version which was released before last update), Second is that you can drop Equipped weapon and it wont remove and you can use it even if u dont have it, Third is that "Equiped" is spelled wrongly, its supposed to be "Equipped". 

Some other issue's.
             :
            V

GPS works even tho you dont have it.
Binoculars doesnt work when you equip it, it just disappears.

I can fix them on my own, isnt that hard but i'm just reminding you that you forgot about theese things as i can see.

**Comment by mihayy5** [comment]
Thank you for the feedback, if you find any other bug please report it here as well.

About the Equipped thing I realized that after I pushed the build, the GPS will get removed and will be an optional addon in the next build.

How the hell haven't I noticed the drop of Equipped weapons bug ?!?!? LOL.

Just to mention R2A1 means 'Release 2 Alpha 1'
Release number will be changed when big changes comes to the gamemode "Alpha X" may change to "Beta X"

Hmm I can't understand way when I equip binoculars It gives me nothing but when I unequip it gives me the binoculars...
Also the Hatchet also remain after I drop/unequip it...
Do you have any idea about those? the script seems to work just fine...

**Comment by rivor2** [comment]
I'm just guessing, i cant really tell because this code is not familiar to me. Need to explore it more but i think problem could be that when you Equip weapon it takes all weapons away and then give's it back.

which should not be like that, atleast i didnt use it in my own equip system that i made a while ago.

`addEventHandler("onPlayerRearmWeapon", root, function(weapon, slot)
	takeAllWeapons(source); -- <---------------------------------------------- i mean this one.
	local wAmmo,_,_ = getWeaponAmmoType(weapon);
	if (getElementData(source, wAmmo) <= 0) then
		triggerClientEvent(source, "displayClientInfo", source, "No mags left for this weapon!", 255, 22, 0);
		return;
	end
	local cWeapon = getElementData(source, "currentweapon_"..tostring(slot));
	if (cWeapon ~= "") then
		setElementData(source, cWeapon, getElementData(source, cWeapon) + 1);
		setElementData(source, cWeapon.." (Equiped)", getElementData(source, cWeapon.." (Equiped)") - 1);
	end
	setElementData(source, weapon, getElementData(source, weapon) - 1);
	setElementData(source, weapon.." (Equiped)", getElementData(source, weapon.." (Equiped)") + 1);
	setElementData(source, "currentweapon_"..tostring(slot), weapon);
	triggerClientEvent(source, "refreshInventoryManual", source);
	equipThem(source, slot);
end);




here is how i did it on my system which is based on 0.6 dayz version and was made a while ago.

`function onPlayerEquipPrimaryWeapon(weaponName,slot)
    -- Checks what weapon slot was used
    local ammoData,weapID = getWeaponAmmoType (weaponName)
    if getElementData(source,ammoData) <= 0 then triggerClientEvent (source, "displayClientInfo", source,"Rearm",shownInfos["nomag"],255,22,0) return end
    setElementData(source,"currentweapon_"..slot,weaponName)
    -- Sets weapon to player
    if getElementData(source, "isPrimaryWeaponEquipped") == false then
        local weapon = getElementData(source,"currentweapon_1")
        if weapon then
            local ammoData,weapID = getWeaponAmmoType (weapon)
            giveWeapon(source,weapID,getElementData(source,ammoData), true )
            setElementData(source, "isPrimaryWeaponEquipped", true)
            triggerClientEvent(source,"refreshInventoryManual",source)
        end
    end
    if elementWeaponBack[source] then
        detachElementFromBone(elementWeaponBack[source])
        destroyElement(elementWeaponBack[source])
        elementWeaponBack[source] = false
    end
    setElementModel(source, getElementData(source,"skin"))
end
addEvent("onPlayerEquipPrimaryWeapon",true)
addEventHandler("onPlayerEquipPrimaryWeapon",getRootElement(),onPlayerEquipPrimaryWeapon)
`

**Comment by mihayy5** [comment]
Sorry but I don't see how this would affect the script. Also in 0.6x was exactly the same thing but made in other way.

**Comment by mihayy5** [comment]
Fixed :) turned out that because of the Equipping system the Ammo was going crazy :)) Also fixed the Hatched thing.
