### ISSUE TITLE
SpawnVehicle

### ISSUE THREAD

**Issue by skyvzla** [mihayy5/mtadayz07#2]
Server vehicle non-stop of Refresh！
Player less of time,No exist Bug！
not any Being given.

**Comment by skyvzla** [comment]
and also other one Bug
ERROR: [DayZ]/dayz/tools/bone_attach/attach_func.lua:117: cannot resume dead coroutine [string "?"]

**Comment by mihayy5** [comment]
The bone attach bug it's a old one, I don't know how to fix it.
About the player not existing I assume you're talking about player with less that 10 minutes not having  bodies after death. That's the way I wanted to be, it's not a bug, look in **accounts.lua** at line 208 and you will understand.
However I don't understand what do you mean by _"Server vehicle non-stop of Refresh"_ can you explain   better?

**Comment by skyvzla** [comment]
vehicle Start be one,server run a period of time rear vehicle refresh point more than one.

**Comment by mihayy5** [comment]
Have you restarted the gamemode? I think it may be a backup bug.

**Comment by skyvzla** [comment]
Server did not stop pass, vehicle all along plus.
Server replaced pass backup! start rear still is exist.

**Comment by mihayy5** [comment]
What do you mean by _pass_ ?
I just updated **vehicles.lua** download it and try to see if the bug persists.

**Comment by skyvzla** [comment]
OK.Let me try

**Comment by skyvzla** [comment]
Find new BUG
Server restart hind tent position able change

**Comment by mihayy5** [comment]
What do you mean ? what is **_hind_** ?

**Comment by skyvzla** [comment]
Server Restart tent x,y increase  ,Coordinate position increase

WARNING: [DayZ]/dayz/tools/slothbot/sbserver.lua:578: Bad argument @ 'giveWeap
on' [Expected weapon-type at argument 2, got nil]

ERROR: [DayZ]/dayz/vehicles.lua:686: attempt to index a boolean value

**Comment by skyvzla** [comment]
use dobackup instruction that arise
ERROR: [DayZ]/dayz/vehicles.lua:686: attempt to index a boolean value

**Comment by skyvzla** [comment]
Server re-establish a new data, server.log is evident seen increased vehicle
[2016-06-14 23:07:41] INFO: Backup done (0 Tents) and (49 Vehs)
[2016-06-15 09:27:39] INFO: Backup done (2 Tents) and (50 Vehs)
