### ISSUE TITLE
Suggestion for Gamemode.

### ISSUE THREAD

**Issue by rivor2** [mihayy5/mtadayz07#22]
Hey!

Good job keeping up the work on this gamemode! Since last time i was here a lot things have changed in this gamemode. I wanted to suggest you to make grenades be blocked by walls/objects that are big enough to block. When you had server still running you had such feature as this it was really neat and useful for few things. Also how can i add new custom weapon with that attached model on bone replacing default one? I tried doing it, put model id over 4000 which was required in script and yet still didn't work.

**Comment by mihayy5** [comment]
Thanks! About the grenade it will be to much work for me, and i don't have
time, and about the weapons can you explain better?

Pe 15 mar. 2017 17:58, "rivor2" <notifications@github.com> a scris:

**Comment by rivor2** [comment]
Weapons. I mean't that custom weapon system what you have made in there, when you use that custom weapon it removes original model from hands and replaces with attach_bone script a weapon model that aims in correct position. I tried adding custom weapon like that by looking how it was implemented in other weapons but i failed, it was showing default weapon instead showing that custom model.

**Comment by rivor2** [comment]
btw, forgot to tell you. While i was modifying this gamemode i found body duplication on death bug (all data including with body duplicates) you can fix it by going to file vehicles.lua to line 524,525,526,527. Each createExplosion means extra body on death near exploding car. I simply just removed those 4 lines of code nothing even changed besides creating more explosions ofcourse, but it's doing that 'cause it's recalling that even 4 more times 'cause it's onVehicleExplode event and it makes extra explosions means extra kilLDayZPlayer being event called. You can also fix it by changing explosion type to different or little bit rewriting that event.

**Comment by mihayy5** [comment]
About the weapons you clearly did something wrong.
Thank you 'bout the explosion bug.

**Comment by rivor2** [comment]
@mihayy5 can you tell me what i'm doing wrong? I added new weapon changed their model to custom model id in core.lua file in that table and it kinda works but only when it shows on back not when you hold it. http://prntscr.com/eko87j http://prntscr.com/eko8af

**Comment by rivor2** [comment]
I actually managed to make it. Looks like you didn't make it for secondary weapons only for primary. http://prntscr.com/ekoj0g it works now weapon attaches. But, the old weapon is still on hands. How can i remove that? Can't find a way to do it.

**Comment by mihayy5** [comment]
Oh, yeah I know you just need to use my **_alpha.txd_** in order to make it invisible. :)
Just as I used it for the other weapons.

**Comment by rivor2** [comment]
@mihayy5 lel, good that i asked. There's no way i would know that. Thanks mate. But this means i have to use custom model for every gun for that specif gun that it makes invisible? Atleast it's how this script made.

**Comment by mihayy5** [comment]
Yep, that's how I did it. :)

**Comment by rivor2** [comment]
@mihayy5 i recommend you also adding teaDecode in login for passwords through server 'cause then client couldn't be able to receive decode key unless the key is by default. Just a little security tip. :smiley:
