### ISSUE TITLE
Bug with ammo

### ISSUE THREAD

**Issue by Naturliskipsius** [mihayy5/mtadayz07#24]
I found bug when you drop ammo its dissapears

**Comment by mihayy5** [comment]
More info please?

**Comment by Naturliskipsius** [comment]
When you drop from inventory on the floor its just dissapears

**Comment by mihayy5** [comment]
You couldn't be more explicit than this.
I mean does it happens for all weapons? Have you changed anything?

**Comment by TheSarrum** [comment]
Because "M1911 Mag", "M9 SD Mag", "Desert Eagle Mag", "PDW Mag" and "MP5A5 Mag" are not in pickups.lua (itemTable "other")

**Comment by mihayy5** [comment]
Thank you!
