### ISSUE TITLE
Inventrory problem

### ISSUE THREAD

**Issue by Naturliskipsius** [mihayy5/mtadayz07#25]
Now i found another bug that for example when you equip item it says 

for example
Desert Eagle {equiped}
in inventory and when you pick items it dissapears sometimes from inventory or when you die and you go to your body you see that deseart eagle [equiped] and when you take it it dissapears or you also can find items like desert eagle [equiped] in cars or loot points and when you take it also dissapears i think it would be better that you take this thing from it because its very bugless i think

**Comment by rivor2** [comment]
They are easy to fix, those were first things i did to gm when i started to modify. Just add check variables when they die or drop item out and if there is item with string (Equipped) then just set their name back to normal.

**Comment by Naturliskipsius** [comment]
> They are easy to fix, those were first things i did to gm when i started to modify. Just add check variables when they die or drop item out and if there is item with string (Equipped) then just set their name back to normal.


Where i should put in inventory.lua ?

**Comment by mihayy5** [comment]
Fixed.
