### ISSUE TITLE
Glue and Mta DayZ 0.7

### ISSUE THREAD

**Issue by DanDi231** [mihayy5/mtadayz07#26]
![mta-screen_2017-03-20_19-33-49](https://cloud.githubusercontent.com/assets/25385439/24115657/5aa46a9c-0da4-11e7-9def-a473e967e979.png)
![mta-screen_2017-03-20_19-34-06](https://cloud.githubusercontent.com/assets/25385439/24115658/5aa4bd8a-0da4-11e7-9ab7-91e1a0f15359.png)

Look This.. Plzz Fix this..
You can kill on this bug.. ;c

**Comment by mihayy5** [comment]
What does this has to do with my gamemode? I don't remember adding any glue to the gamemode.

**Comment by Naturliskipsius** [comment]
Its not the bug its just you dont know how to use it and maybe u use wrong script because i have this glue also but there are no any problems like that and you should write that guy who made this glue script it must be his problem not mihayy because hes working only with dayz not with other scripts
