### ISSUE TITLE
DayZ spawn player

### ISSUE THREAD

**Issue by WorldOfStrangers** [mihayy5/mtadayz07#3]
Hello,
 I rework a little your fixed dayz version all works fine I hope becouse I don't have any error's or warning in console on startup but when I Register on server I have a black screen when try relog and loggin I spawn but as CJ and bugged to the texture. This error is in console after spawn:

`[16:24:59] ERROR: dayz/script/server/system/ucty.lua:154: attempt to call field 'size' (a nil value)`

New I have this error too:

`dayz/script/server/vozidla/vraky_nemocnice.lua:110: attempt to call field 'percentChance' (a nil value)`

Here you go this two script files: [http://worldofstrangers.eu/download/errors.zip](http://worldofstrangers.eu/download/errors.zip)

**Comment by mihayy5** [comment]
That's because you forgot to also add those two functions:

```
function table.size(tab)
	local length = 0;
	for _ in pairs(tab) do length = length+1 end
	return length;
end

function math.percentChance(percent, repeatTime)
	local hits = 0;
	for i = 1, repeatTime do
		local number = math.random(0, 200)/2
		if number <= percent then hits = hits+1; end
	end
	return hits;
end
```

**Comment by WorldOfStrangers** [comment]
Yeah thanks :D My mistake. :D
