### ISSUE TITLE
Helicrashes

### ISSUE THREAD

**Issue by DanDi231** [mihayy5/mtadayz07#30]
125125 helicrashes on 1 spawn... plzz fix this <3
![mta-screen_2017-04-03_15-02-35](https://cloud.githubusercontent.com/assets/25385439/24829438/f716e112-1c71-11e7-8ef0-e51328ad7904.png)
![mta-screen_2017-04-03_15-05-09](https://cloud.githubusercontent.com/assets/25385439/24829441/fc0ff26c-1c71-11e7-9950-8979eb364af2.png)

**Comment by mihayy5** [comment]
Modified gamemode you did something wrong! Just tested the original code!
