### ISSUE TITLE
Zombie death falling items

### ISSUE THREAD

**Issue by skyvzla** [mihayy5/mtadayz07#33]
onZombieGetsKilled event under

`	for _,v in ipairs(itemTableZombies) do
		local value = math.percentChance(v[2]/2.5, 1);
		setElementData(pedCol, v[1], value);
		local ammoData,_ = getWeaponAmmoType(v[1]);
		if (ammoData and value > 0) then
			setElementData(pedCol, ammoData, 1);
		end
	end`
When it is a **Hunting Knife**, the return is **Hunting Knife (Equipped)**
So, when the zombies die will fall **Hunting Knife** and **Hunting Knife (Equipped)**

**Comment by mihayy5** [comment]
Fixed!
