### ISSUE TITLE
Can't loot tent

### ISSUE THREAD

**Issue by GribixTugaZ** [mihayy5/mtadayz07#38]
![mta-screen_2017-05-28_17-13-54](https://cloud.githubusercontent.com/assets/26173703/26530243/2ed5d5d2-4386-11e7-9c93-c8e682bdf35e.png)
This is a resource that i downloaded by the way.It makes it so that i can get all the items i want,just by looting the tent.

**Comment by mihayy5** [comment]
You have modified the code, why have you created this issue number? Ask for
help on mta forum.

Pe 28 mai 2017 19:16, "GribixTugaZ" <notifications@github.com> a scris:

**Comment by GribixTugaZ** [comment]
Thanks anyway.
