### ISSUE TITLE
Another error with core_client

### ISSUE THREAD

**Issue by WorldOfStrangers** [mihayy5/mtadayz07#4]
Hello it's me again :D I have a problem with core_client this part of script don't work I give you my copy of your original core_client.lua and there is a new issue with this: 
`ERROR: dayz/script/server/vozidla/vraky_nemocnice.lua:144: attempt to index global 'hospitalCol' (a nil value)`

Here is link to the copy of core:
[jadro_systemu.zip](https://github.com/mihayy5/mtadayz07/files/298907/jadro_systemu.zip)

I don't know why it didn't work because all other edited parts are working properly...
PS: I'm sorry to bother you.

**Comment by mihayy5** [comment]
You gave me the wrong code.

**Comment by WorldOfStrangers** [comment]
No I have two issues one with "vraky_nemocnice" and one with core_client becouse core_client not working on server. I gave you vraky_nemocnice too.
[vraky_nemocnice.zip](https://github.com/mihayy5/mtadayz07/files/298916/vraky_nemocnice.zip)

**Comment by mihayy5** [comment]
You need to add this on top of the code

`local hospitalCol = {};`

Next time when you delete something make sure you don't delete something important.
