### ISSUE TITLE
Weapon sounds

### ISSUE THREAD

**Issue by Stifler98** [mihayy5/mtadayz07#42]
How can i change the weapons sounds?

And, where can i change the items spawning probability?
{"AKS Gold",1835,1,90,2.4} = item name, ID, object scale, rotX, spawn probability (I think)
But when i rewrote the "pobability" to 0, nothing changed and i found it again.. :(

**Comment by mihayy5** [comment]
Make sure you rewrite it on all tables.
About the weapon sound you can get help on MTA Forums for that.
