### ISSUE TITLE
That problem from yesterday is back

### ISSUE THREAD

**Issue by WorldOfStrangers** [mihayy5/mtadayz07#6]
Hi,
 That problem with inventory is back... If you have some free time please chcek the inventory code. Thank you.
 Here you are the code:
[ruksak.zip](https://github.com/mihayy5/mtadayz07/files/299480/ruksak.zip)

**Comment by mihayy5** [comment]
What problem ? Describe.

**Comment by WorldOfStrangers** [comment]
When I join to the test server the some part of inventory windows are visible and bugged but I can't click on them I send you a screenshots here.
![screen1](https://cloud.githubusercontent.com/assets/19748872/15807856/71326b2a-2b68-11e6-8f89-072d3c46ae3f.png)
![screen2](https://cloud.githubusercontent.com/assets/19748872/15807858/7bb52664-2b68-11e6-9687-66f731f3ed5a.png)

**Comment by mihayy5** [comment]
Well that's you're modified version of script I can't give you support with that.
