### ISSUE TITLE
Pickups and lootspawns

### ISSUE THREAD

**Issue by WorldOfStrangers** [mihayy5/mtadayz07#7]
Hi,
 Finally I fix that isue with inventory I completly rework my custom DayZ with backup of original files but now I have in console this error:
ERROR: dayz/script/server/loot.lua:397: attempt to index global 'pickupPositions' (a nil value)
I don't edit anything in pickups or lootspawns I only rewrite the name of this files.

**Comment by mihayy5** [comment]
Well have you changed the position in meta.xml ? That can
