### ISSUE TITLE
vehicle and zombie

### ISSUE THREAD

**Issue by skyvzla** [mihayy5/mtadayz07#8]
Server re-establish a new data, server.log is evident seen increased vehicle
[2016-06-14 23:07:41] INFO: Backup done (0 Tents) and (49 Vehs)
[2016-06-15 09:27:39] INFO: Backup done (2 Tents) and (50 Vehs)
WARNING: [DayZ]\dayz\tools\slothbot\sbserver.lua:578: Bad argument @ 'giveWeapon' [Expected weapon-type at argument 2, got nil]

**Comment by mihayy5** [comment]
About the slothbot error I don't know why I get that error.
And the vehicle backup, are you sure you haven't spawned any vehicles meanwhile?
I also see 2 tents instead of 0, that's why I'm asking.

**Comment by skyvzla** [comment]
tents is me discharge the .
I did not move   vehicle. No added

**Comment by skyvzla** [comment]
which country are you from

**Comment by mihayy5** [comment]
Romania.

**Comment by skyvzla** [comment]
you have Skype?

**Comment by mihayy5** [comment]
Esti roman ?!?

**Comment by skyvzla** [comment]
microsoft chat - ul

**Comment by skyvzla** [comment]
When a vehicle into the water, it will spawn two vehicles, the explosion of the vehicle is also like this

**Comment by skyvzla** [comment]
I will be the server IP and password to you, you go to the background to see

**Comment by skyvzla** [comment]
Am găsit în cazul în care problema

addEventHandler("onVehicleExplode", getRootElement(),  function()
	for _,v in pairs(getVehicleOccupants(source)) do
		triggerEvent("kilLDayZPlayer", v);
	end
	local col = getElementData(source, "parent");
	local x1,y1,z1 = getElementPosition(source);
	if col and isElement(col) then
		id,x,y,z = getElementData(col, "spawn")[1], getElementData(col, "spawn")[2], getElementData(col, "spawn")[3], getElementData(col, "spawn")[4]
		setElementData(col, "deadVehicle", true);
	end
	setElementData(source, "isExploded", true);
	if (getElementData(source, "dayzvehicle") == 1) then
		setTimer(respawnDayZVehicle, 1800000, 1, id, x, y, z, source, col);
	else
		setTimer(function(col, source)
			if isElement(col) then destroyElement(col); end
			if isElement(source) then destroyElement(source); end
		end, (5*60000), 1, col, source);
	end
	createExplosion((x1+4), (y1+1), z1, 4);
	createExplosion((x1+2), (y1-4), z1, 4);
	createExplosion((x1-1), (y1+5), z1, 4);
	createExplosion((x1-4), y1, (z1-2), 4);
end);

setTimer(function()
	for _,v in ipairs(getElementsByType("vehicle")) do
		if (getElementModel(v) ~= 453) then
			if isElementInWater(v) then
				local col = getElementData(v, "parent");
				local id,x,y,z = getElementData(col, "spawn")[1], getElementData(col, "spawn")[2], getElementData(col, "spawn")[3], getElementData(col, "spawn")[4];
				if (getElementData(v, "dayzvehicle") == 1) then
					setTimer(respawnDayZVehicle, 1800000, 1, id, x, y, z, v, col, getElementData(col, "MAX_Slots"));
				else
					setTimer(function(col, v)
						if isElement(col) then destroyElement(col); end
						if isElement(v) then destroyElement(v); end
					end, (5*60000), 1, col, v);
				end
			end
		end
	end
end, (20*60000), 0);

În cazul în care explozia și a căzut în apă în timp ce există, ea va perie multiple!
